spring:
  application:
    name: live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:db-sharding.yaml
    hikari:
      pool-name: user-pool
      minimum-idle: 150
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: wsl
      lettuce:
        pool:
          min-idle: 10 #最小空闲数
          max-active: 50 #最大活跃数
          max-idle: 20 #最大空闲数
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848?namespace=live-test&&username=LIMBO&&password=LIMBO
  protocol:
    name: dubbo
    port: 9091

rocketmq:
  producer:
    name-server: wsl:9876
    group-name: ${spring.application.name}
    retry-times: 3
    send-time-out: 3000
  consumer:
    name-server: wsl:9876
    group-name: ${spring.application.name}
